name: stripe_payment_example
description: Demonstrates how to use the stripe_payment plugin.

dependencies:
  http:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  stripe_payment:
    path: ../
  e2e: ^0.4.2
  flutter_driver:
    sdk: flutter
    
flutter:
  uses-material-design: true
